# -*- coding: utf-8 -*-
"""sentencesimilarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cSnzlk1a1Ic0ic-TpAQK1mnDtVxPNrC2
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
#load the mode1
mode1 = SentenceTransformer('all-MiniLM-L6-v2')
#take input from user
text1 = input("Enter Text 1: ")
text2 = input("Enter Text 2: ")
#convert text to embeddings
embedding1 = mode1.encode(text1)
embedding2 = mode1.encode(text2)
#calculate similarity
similarity = util.cos_sim(embedding1, embedding2)
#show result
print("\nsimilarity score:", round(float(similarity), 2))
if similarity > 0.75:
    print("Similarity Level: High")
elif similarity > 0.4:
    print("Similarity Level: Medium")
else:
    print("Similarity Level: Low")