# -*- coding: utf-8 -*-
"""text generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlEeVF3p3SRvstE-eZU2vHVEyinSC2eK
"""

!pip install transformers torch

from transformers import pipeline

#toad text generation model (GenAI)

generator = pipeline("text-generation", model="gpt2")

#Input prompt

prompt="Aritificial Intelligence in finance will"

#Generate text

result = generator (prompt, max_length=50, num_return_sequences=1)

print("AI generated Text:")

print(result[0]['generated_text'])